### ISSUE TITLE
Shield Issues

### ISSUE THREAD

**Issue by ZephyrWarrior** [aeoncleanse/Mods#229] opened 2017-08-27 00:59 UTC
When playing a game with a friend (Cybran-UEF vs Aeon CPU), neither my nor his shield generators functioned at all. No dome went up. However, the opposing Aeon tech 2 tanks had invincible shields. We can try to type up replication instructions if you can't replicate this bug.

**Comment by AndroTritium** [comment] 2017-08-27 01:00
The UEF commander units had a shield unit active, however our shield generators, both Tier 2 and 3 were non functional.

**Comment by MrNukealizer** [comment] 2017-08-27 01:49
A replay ID would be extremely helpful for this. My gut feeling is that it's a mod bug. Did you have any mods active?

Edit: I was dumb, see below.

**Comment by ZephyrWarrior** [comment] 2017-08-27 04:31
https://puu.sh/xkvRe/fb2f3b1dd4.fafreplay

There you are. I'm not sure how to publish it.

**Comment by ZephyrWarrior** [comment] 2017-08-27 05:50
And to the second part of your question, only the 5 mods in this package.

**Comment by MrNukealizer** [comment] 2017-08-27 06:13
Oh, my bad. I forgot I would get notifications of issues here so I thought this was in a different repository. This does appear to be the correct place for this issue.

Unless you were specifically testing it, I recommend not using SharedArmies. It requires a patched exe and is in very early development. It probably won't work right before version 4, and maybe not even then.

I don't think SharedArmies was the cause of your shield problems, but the replay desyncs hard at about 55 seconds for me, so I can't tell what was really going on.

**Comment by ZephyrWarrior** [comment] 2017-08-27 06:18
We'll run a game without shared armies and rush for shields so hopefully you'll be able to see. Will update when that's done.

Disabled Shared Armies as well as Tweaks, and shields appear to be in working order. Will update if the bug reappears. Thanks!

**Comment by Uveso** [comment] 2017-09-02 18:40
@ZephyrWarrior:

Any new problems with shields the last week ?
if not, please close this issue. Thanks!

**Closed as completed** 2017-09-09 20:01 UTC
